# Test 2026-09-12 at 03:06:14

name: compactCochiseHouse

on:
  push:
    paths:
      - '**/main.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install Perl packages
      run: |
        sudo cpan install Data::Table::Text Data::Dump Svg::Simple

    - name: Perl
      run: |
        perl floorPlan.pl
